In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
import numpy as np

# 3.1 用于数组的文件输入输出

## 将数组以二进制格式保存到磁盘

`np.save` 和 `np.load` 是读写磁盘数组数据的两个主要函数

默认情况下，数组是以未压缩的原始二进制格式保存在扩展名为`.npy`的文件中的。

`np.savez` 可以将多个数组保存到一个压缩文件中，将数组以关键字参数的形式传入即可

In [2]:
arr = np.arange(10)

np.save('some_array', arr)
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.savez('array_archive.npz', a=arr, b=arr)
# 加载.npz文件时，会得到一个类似字典的对象，该对象对各个数组进行延迟加载
arch = np.load('array_archive.npz')
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
import os 
for f in ['array_archive.npz', 'some_array.npy']:
    os.remove(f)

## 存取文本文件

`np.loadtxt` 

`np.savetxt`

`np.genfromtxt`

In [5]:
# arr = np.loadtxt('array_ex.txt', delimiter=',')
# np.savetxt执行的是相反的操作，将数组写到以某种分隔符隔开的文本文件中

<br><br><br>
# 3.2 线性代数

In [6]:
x = np.array([[1.,2.,3.], [4.,5.,6.]])
y = np.array([[6.,23.], [-1, 7], [8, 9]])
x
y
x.dot(y) # or np.dot(x, y)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

array([[  6.,  23.],
       [ -1.,   7.],
       [  8.,   9.]])

array([[  28.,   64.],
       [  67.,  181.]])

In [7]:
# 二维数组跟一个大小合适的一维数组的矩阵点积后得到一维数组
np.dot(x, np.ones(3))

array([  6.,  15.])

In [8]:
from numpy.linalg import inv, qr
X = np.random.randn(5,5)
mat = X.T.dot(X)
inv(mat)
mat.dot(inv(mat))
q, r = qr(mat)
r

array([[ 0.89725049, -0.21313714,  0.78486733, -0.00255519, -0.14397198],
       [-0.21313714,  1.05569583,  0.28903951,  0.53849548,  0.37313249],
       [ 0.78486733,  0.28903951,  1.63715448,  0.34571921, -0.1841018 ],
       [-0.00255519,  0.53849548,  0.34571921,  0.39725107,  0.13802863],
       [-0.14397198,  0.37313249, -0.1841018 ,  0.13802863,  0.33043981]])

array([[  1.00000000e+00,   0.00000000e+00,  -1.66533454e-16,
         -5.55111512e-17,   0.00000000e+00],
       [ -2.22044605e-16,   1.00000000e+00,  -3.33066907e-16,
          2.22044605e-16,   0.00000000e+00],
       [  1.11022302e-16,  -3.33066907e-16,   1.00000000e+00,
          0.00000000e+00,   0.00000000e+00],
       [ -5.55111512e-17,   6.66133815e-16,   2.49800181e-16,
          1.00000000e+00,   4.99600361e-16],
       [  0.00000000e+00,  -4.44089210e-16,  -2.22044605e-16,
          4.44089210e-16,   1.00000000e+00]])

array([[ -4.26533836,  -6.54343884,   3.60396016,   3.28226038,   7.3983154 ],
       [  0.        ,  -7.09323519,  -0.70837325,  10.72376685,
          3.90090747],
       [  0.        ,   0.        ,  -1.51242539,   3.93566644,
         -4.41031775],
       [  0.        ,   0.        ,   0.        ,  -1.56104101,
          1.15393388],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          1.76201776]])

### 常用的线性代数函数

#### numpy命名空间中的方法

函数 | 说明
--- | ---
`diag` | 以一维数组的形式返回方阵的对角线（或非对角线）元素，<br>或将一维数组转换为方阵（非对角线元素为0）
`dot` | 矩阵乘法
`trace` | 对角线元素的和

#### numpy.linalg 函数

函数 | 说明
--- | ---
`det` | 计算矩阵行列式
`eig` | 计算方阵的特征值和特征向量
`inv` | 计算矩阵的逆
`pinv` | 计算矩阵的Moore-Penrose伪逆
`qr` | 计算QR分解
`svd` | 计算奇异值分解(SVD)
`solve` | 解线性方程组$Ax = b$，其中A为一个方阵
`lstsq` | 计算$Ax = b$的最小二乘解

<br><br><br>
# 3.2 随机数生成

In [9]:
# normal 得到标准正态分布
samples = np.random.normal(size=(4,4))
samples

array([[-1.24709117, -1.01705839, -0.88832428, -1.25288055],
       [-1.04098613,  0.4174277 , -0.42381768, -0.66490345],
       [ 1.10180005, -0.9287201 , -1.21345075, -1.4253554 ],
       [ 0.11408865,  1.34749776,  0.73270568, -1.11160727]])

In [10]:
from random import normalvariate
N = 1000000
%timeit samples = [normalvariate(0,1) for _ in range(N)]
%timeit np.random.normal(size=N)

1 loop, best of 3: 1.45 s per loop
10 loops, best of 3: 71.2 ms per loop


### 部分numpy.random函数

函数 | 说明
--- | ---
`seed` | 确定随机数生成器的种子
`permutation` | 返回一个序列的随机排列或返回一个随机排列的范围
`shuffle` | 对一个序列就地随机排列
`rand` | 产生均匀分布的样本值
`randint` | 从给定的上下限范围内随机选取整数
`randn` | 产生正态分布（平均值为0，标准差为1）的样本值
`binomial` | 产生二项分布的样本值
`normal` | 产生正态（高斯）分布的样本值
`beta` | 产生Beta分布的样本值
`chisquare` | 产生卡方分布的样本值
`gamma` | 产生Gamma分布的样本值
`uniform` | 产生在[0, 1)中均匀分布的样本值